development:
  adapter: postgresql
  encoding: unicode
  database: turnchannelfm_development
  pool: 5
  username: turnchannel
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: turnchannelfm_test
  pool: 5
  username: turnchannel
  password:
