development:
  common:
    app_hostname:   http://dev.turnchannel.fm:3000

  # turnchannel.studio@gmail.com account
  soundcloud:
    auth_url:       https://soundcloud.com/connect
    token_url:      https://api.soundcloud.com/oauth2/token

    client_id:      e3216af75bcd70ee4e5d91a6b9f1d302
    client_secret:  045f441b8d70932bca6b0afceb701486

# ============

test:
  common:
    app_hostname:   http://dev.turnchannel.fm:3000

  # turnchannel.studio@gmail.com account
  soundcloud:
    auth_url:       https://soundcloud.com/connect
    token_url:      https://api.soundcloud.com/oauth2/token

    client_id:      e3216af75bcd70ee4e5d91a6b9f1d302
    client_secret:  045f441b8d70932bca6b0afceb701486
